### PR TITLE
Small code improvements

### PR DESCRIPTION
**Pull request by ZackeryRSmith**
Slight comment cleanups, replaced `"\n".join(["line1", "line2"])` syntax with multi-line strings, removed unnecessary parts of the gitignore file.

**Why I removed the `hello` command**
I decided to remove the `hello` command as it isn't very intuitive. As you probably know, Discord.py doesn't and won't support slash command aliases ([see here](https://github.com/discord/discord-api-docs/issues/2323#issuecomment-761137779)). I've instead opted for the `hello` command's alias `givemebadge`.

Hope you found this PR is helpful in some way

### CODE REVIEW

**Comment by SomeHybrid** [comment]
I don't think using the backslash with `"""\` is necessary.
Also, for the gitignore, most of the stuff in there is due to IDEs and packaging systems, etc.

**Comment by ZackeryRSmith** [comment]
> I don't think using the backslash with """\ is necessary.

It's definitely not required but it looks better then one giant line of text. Due to my screw size it causes line wrapping and it looks pretty ugly

As far as the other things in the gitignore after overlooking it I don't see anything that stands out as an IDE generated file and or folder. All the stuff (or at least the great majority) of the things I removed from the gitijnore isn't useful for this project.

**Comment by SomeHybrid** [comment]
What i meant is that
```
"""\
this
that
there
"""```

is the same as
```
"""
this
that
there
"""

**Comment by ZackeryRSmith** [comment]
It's not. Doing it like you showed adds an extra space at the top.

```
Python 3.10.6 (main, Nov  2 2022, 18:53:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> print("""
... This
... That
... There""")

This
That
There
>>> print("""\
... This
... That
... There""")
This
That
There
```
This kind of behavior also occurs when storing the multi-line string in a variable.

**Comment by AlexFlipnote** [comment]
I have made an update that takes usage of `inspect.cleandoc` instead for the majority of triple quote lines. This is to keep the indent and code clean and readable as much as possible.

**Pull request closed without merging**
