### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 0xb4dc0d3x**
source code usage section changed  
terminal commands per OS changed
use some emojis to make it beautiful

### CODE REVIEW

**Comment by AlexFlipnote** [comment]
Do you really need to do python3.9 on Debian? 
image

**Comment by AlexFlipnote** [comment]
Other than that the PR looks nice

**Comment by 0xb4dc0d3x** [comment]
Hi, I used your source code to deploy it on my Ubuntu server and I've got some errors. and because of that I changed your readme to make it easy to copy and use. I can delete the Debian section =)

**Comment by AlexFlipnote** [comment]
> Hi, I used your source code to deploy it on my Ubuntu server and I've got some errors. and because of that I changed your readme to make it easy to copy and use. I can delete the Debian section =)

no no you don't need to lmaooo. Was simply asking since I use Debian myself and it does not need the 3.9 suffix for me. Might be because I installed it using `pyenv` and not with `apt-get`, but yeah. If that is the most standard, I would keep it like that.

**Comment by 0xb4dc0d3x** [comment]
then I add Debian section too, lmao
and the output of `python` on my terminal:

Screenshot from 2022-11-20 18-22-18

**Comment by AlexFlipnote** [comment]
Looks good to me :)

**Pull request merged**
