### PR TITLE
Create edits for user experience

### PR DESCRIPTION
**Pull request by DaInfLoop**
https://github.com/AlexFlipnote/GiveMeBadge/commit/8b74f040082c161ccbae4056e1f85b590f9a9457 - Fix a minor spelling mistake in `_init_command_response`'s function description

https://github.com/AlexFlipnote/GiveMeBadge/commit/291e7100bf45773bedd93d034b020853e4dfcd97 - Make the message look cleaner + Add a section on what if I don't get the badge in 24 hours

https://github.com/AlexFlipnote/GiveMeBadge/commit/0e43bbc8a3c0a4ca52a1d1a9491464257d942c88 - Make the `GiveMeBadge` window close after running `/hello` or `/givemebadge`

example

### CODE REVIEW

**Comment by DaInfLoop** [comment]
> I would not automaitcally close the window, as people can get scared of that. Otherwise I approve the grammar changes and stuff. :+1:

Alright, I'll remove those changes tomorrow

**Comment by AlexFlipnote** [comment]
Any updates?

**Comment by DaInfLoop** [comment]
> Any updates?

Forgot about this lmao, thanks to @ZackeryRSmith for adding the changes though

**Comment by ZackeryRSmith** [comment]
> > Any updates?
> 
> Forgot about this lmao, thanks to @ZackeryRSmith for adding the changes though

No problem!

**Pull request closed without merging**
